### ISSUE TITLE
対応DBについて

### ISSUE THREAD

**Issue by hinoko58** [gomachssm/twsqlparser#5]
魅力的なライブラリありがとうございます。

このライブラリはmysql(もしくはmariadb)は対応していますか？

django2で利用したいと思いますが、サンプルが見つかりませんでした。
もし対応しているなら参考ページまたはサンプルソースを教えていただけますか？

よろしくおねがいします。

**Comment by gomachssm** [comment]
@hinoko58 
このライブラリ自体はDBに接続する機能を持っていないので、別のDB接続ライブラリと組み合わせて利用していただければと思います。
MySQL、MariaDBで利用できるpyformat方式がこのライブラリに近そうでしたが、残念ながらこのライブラリでは現状、非対応になります。
djangoを利用したいとのことでしたので、大体としてPostgreSQLを利用されてはどうでしょうか？

pyformat形式の対応も検討したいと思います。

**Comment by gomachssm** [comment]
@hinoko58 さん
追記になります。
SQLAlchemyであれば本モジュールを利用した開発が行えるかもしれません。
こちらを参照ください。https://docs.sqlalchemy.org/en/14/core/tutorial.html#using-textual-sql
twsqlparser.parse_fileまたはtwsqlparser.parse_sqlの1つ目の戻り値(str)をtext()に、2つ目の戻り値をconn.executeの第2引数に指定してください。
リンク先サンプルを参考に、本モジュールを利用した例を記載します。
```python
sql, params = twsqlparser.parse_sql(base_sql, base_params)
s = text(sql)
conn.execute(s, params).fetchall()
```

**Comment by gomachssm** [comment]
postgres、mysqlを利用したサンプルコードをコミットしました。
https://github.com/gomachssm/twsqlparser/tree/master/sample

**Comment by gomachssm** [comment]
@hinoko58 だいぶ遅くなってしまい申し訳ありません。サンプルコードをコミットしましたので、このissueをクローズしても良いでしょうか。

**Comment by hinoko58** [comment]
@gomachssm ご丁寧に対応いただき、ありがとうございます。😁😁
本ライブラリを重宝しています。チームメンバーから高評価です。
素晴らしいライブラリありがとうございます。
